server:
  servlet:
    context-path: /notibback
  error:
    path: /error
  forward-headers-strategy: framework
spring:
  mvc:
    view:
      prefix: /WEB_INF/jsp/
      suffix: .jsp
  freemarker:
    enabled: false
  messages:
    basename: messages
  liquibase:
    enabled: false
    contexts: undefined
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  jpa:
    open-in-view: false
  jmx:
    enabled: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"

#springdoc:
#  packages-to-scan: es.caib.notib.api.interna.controller
#  api-docs.path: /api-docs
#  swagger-ui:
#    path: /rest
#    operationsSorter: method